# Create a workflow for Github Action to build the docker image
# and push it to the docker hub

name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Login to Docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./api
        file: ./api/Dockerfile
        push: true
        tags: studyabacus/exam-api:latest

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Copy docker-compose file
      uses: appleboy/scp-action@v0.1.7
      with:
        key: ${{ secrets.SSH_KEY }}
        username: studyabacus
        host: ${{ secrets.SRV2_HOST }}
        source: ".github/deployment/docker-compose.yaml"
        target: "/home/studyabacus/servers/exam-api/docker-compose.yaml"

    - name: Update application version
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SRV2_HOST }}
        username: studyabacus
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/studyabacus/servers/exam-api && docker-compose pull && docker-compose up -d

