# Create a workflow for Github Action to build the docker image
# and push it to the docker hub

name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./api
        file: ./api/Dockerfile

